include: "rules/common.smk"
include: "rules/inputfunctions.smk"

configfile: "config/config.yaml"

# Flatten species-specific references into the top-level config
species = config["species"]
for key, value in config["resources"][species].items():
    config[key] = value

rule all:
    input:
        unpack(all),


# Pseudo-target using expand
rule all_qc:
    input:
        all_qc_fastqc,

include: "rules/qc.smk"
include: "rules/align.smk"
include: "rules/index.smk"
include: "rules/prnrd.smk"
include: "rules/revertsam.smk"
include: "rules/samtofq.smk"
include: "rules/mitoaln.smk"
include: "rules/mitoaln_shft.smk"
include: "rules/mergmt_ref.smk"
include: "rules/mergmt_shft.smk"
include: "rules/rdup_ref.smk"
include: "rules/rdup_shf.smk"
include: "rules/sort_ref.smk"
include: "rules/sort_shft.smk"
include: "rules/collect_metrics_ref.smk"
include: "rules/collect_metrics_shft.smk"
include: "rules/mutect_ref.smk"
include: "rules/mutect_shf.smk"
include: "rules/haplo.smk"
include: "rules/lift.smk"
include: "rules/mergevcf.smk"
include: "rules/filter.smk"
include: "rules/variant_filtration.smk"
#include: "rules/annot.smk"
