### Sample maps ###
reads: "config/reads.tsv"
samples: "config/samples.tsv"
species: "mouse" # Set to "mouse" or "human"

### Mouse - mm39 (GRCm39) ### 
ref: "resources/mm39/GCF_000001635_27_GRCm39_genomic.fna"
dict: "resources/mm39/GCF_000001635_27_GRCm39_genomic.dict"
mt_chrom_name: "NC_005089.1"
mt_ref: "resources/mm39/chrMT.fna"
mt_shft_ref: "resources/mm39/chrMT_shifted_8000bp.fna"
mt_back_chain: "resources/mm39/chrMT_shifted_8000bp.back_chain"
mt_shft_control_region: "resources/mm39/control_region_chrMT_shifted_8000bp.bed"
mt_non_control_region: "resources/mm39/non_control_region_chrMT.bed"

### Human - hg38 (GRCh38) ###
#ref: 
#dict:
#mt_chrom_name: "resources/hg38/"
#mt_ref: "resources/hg38/hg38.chrM.fa"
#mt_shft_ref: "resources/hg38/hg38.chrM.shifted8000.fa"
#mt_back_chain: "resources/hg38/ShiftBack.chain"
#mt_shft_control_region: "resources/hg38/hg38_v0_chrM_control_region_shifted.chrM.interval_list"
#mt_non_control_region: "resources/hg38/non_control_region.chrM.interval_list"

### Params Variant Calling ###
filter:
  minAF: 0.01
  min_reads_per_strand: 2

### Tools ###
bwa: 
  threads: 40

fastqc:
  mem_mb: 1024
  threads: 8

gatk:
  container: "singularity/gatk.sif" 
  mem_mb: 4096
  threads: 32


picard:
  container: "singularity/picard.sif"
  mem_mb: 1024 
  threads: 32

samtools:
  threads: 8

vep:
  container: "singularity/vep.sif"
  threads: 4