### Sample maps ###
reads: "config/reads.tsv"
samples: "config/samples.tsv"
fastq_dir: "data/raw" # Should be "data/raw" by default
species: "human" # Set to "mouse" or "human"

resources:
  mouse:
    ### Mouse - mm39 (GRCm39) ### 
    ref: "resources/mm39/GCF_000001635_27_GRCm39_genomic.fna"
    dict: "resources/mm39/GCF_000001635_27_GRCm39_genomic.dict"
    mt_chrom_name: "NC_005089.1"
    mt_ref: "resources/mm39/chrMT.fna"
    mt_shft_ref: "resources/mm39/chrMT_shifted_8000bp.fna"
    mt_back_chain: "resources/mm39/chrMT_shifted_8000bp.back_chain"
    mt_shft_control_region: "resources/mm39/control_region_chrMT_shifted_8000bp.bed"
    mt_non_control_region: "resources/mm39/non_control_region_chrMT.bed"

  human:
    ### Human - hg38 (GRCh38) ###
    ref: "resources/hg38/GCF_000001405.40_GRCh38.p14_genomic.fna"
    dict: "resources/hg38/GCF_000001405.40_GRCh38.p14_genomic.dict"
    mt_chrom_name: "NC_012920.1"
    mt_ref: "resources/hg38/chrMT.fna"
    mt_shft_ref: "resources/hg38/chrMT_shifted_8000bp.fna"
    mt_back_chain: "resources/hg38/chrMT_shifted_8000bp.back_chain"
    mt_shft_control_region: "resources/hg38/control_region_shifted_8000bp_chrMT.bed"
    mt_non_control_region: "resources/hg38/non_control_region_chrMT.bed"

### Params Variant Calling ###
filter:
  minAF: 0.01
  min_reads_per_strand: 2

### Tools ###
bwa: 
  threads: 24

fastqc:
  mem_mb: 1024
  threads: 8

gatk:
  container: "singularity/gatk.sif" 
  mem_mb: 4096
  threads: 24


picard:
  container: "singularity/picard.sif"
  mem_mb: 1024 
  threads: 24

samtools:
  threads: 8

vep:
  container: "singularity/vep.sif"
  threads: 4