# This config file is made according to Nextseq run and to be standardized based on other sequencers
indir: inputdir
outdir: outputdir
genome: testdata
mcid: "Machineid" # Required to automatically fetch the sample location created from Nextseq run
samplescount: 3  # No of samples
